name: Apache Server

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Allow external access
        run: |
          sudo ufw allow 'Apache Full'
          sudo ufw --force enable
      - name: Set up Apache server
        run: |
          sudo apt-get update
          sudo apt-get install apache2 -y
          sudo service apache2 start

