name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Check container
        uses: docker://azlux/botamusique:latest
        with:
            BAM_CONFIG_file: ./botamusique.ini
            BAM_MUSIC_DB: ./music.db
            BAM_DB: ./setting-xana.db
